#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

# Run the 3d simulations
cd Simulation_3d/
python -u main_segment.py "$@"
python -u main_CNN.py "$@"
python -u plottrain.py "$@"
python -u main_evCNN.py "$@"
python -u main_evCNN_error.py "$@"
python -u main_shap.py "$@"
python -u readshap.py "$@"

# Run the 2d experiments
cd ../Experiment_2d/
python -u main_segment.py "$@"
python -u main_CNN.py "$@"
python -u plottrain.py "$@"
python -u main_evCNN_compare.py "$@"
python -u main_evCNN_error.py "$@"
python -u main_evCNN.py "$@"
python -u main_shap.py "$@"
python -u readshap.py "$@"
# Run the 2d experiments for node influence
cd ../Experiment_2d_point/
python -u main_shap.py "$@"
python -u readshap_deep.py "$@"

echo "Final"

